# ===== JavaScript =====
[[plugins]] # prettier
repo = 'prettier/vim-prettier'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
hook_add = '''
  nnoremap <Leader>p :Prettier<CR>
  let g:ale_fixers = {
  \  '*': ['remove_trailing_lines', 'trim_whitespace'],
  \  'javascript': ['eslint'],
  \}
'''


# ===== Python =====
[[plugins]] # Python syntax
repo = 'hdima/python-syntax'
on_ft = ['python']


[[plugins]] # Python 補完
repo = 'davidhalter/jedi-vim'
on_ft = ['python']


[[plugins]] # jediをdeopleteで使用するための依存関係
repo = 'zchee/deoplete-jedi'
on_ft = ['python']


# ===== toml =====
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = ['toml']
